services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: task_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - task_network

    nginx:
        image: nginx:alpine
        container_name: task_nginx
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
        networks:
            - task_network

    mysql:
        image: mysql:latest
        container_name: task_mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - task_network

    redis:
        image: redis:alpine
        container_name: task_redis
        restart: unless-stopped
        ports:
            - "6379:6379"
        networks:
            - task_network

    laravel-horizon:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: task_horizon
        restart: unless-stopped
        command: php artisan horizon
        volumes:
            - ./:/var/www
        networks:
            - task_network

networks:
    task_network:
        driver: bridge

volumes:
    mysql_data:
        driver: local
